spring:
  application:
    name: eoc-ko-back
  profiles:
    active: local # 기본 활성 프로필을 'local'로 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          # ================= GOOGLE =================
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID_HERE  # 여기에 구글 클라이언트 ID 입력
            client-secret: YOUR_GOOGLE_CLIENT_SECRET_HERE # 여기에 구글 클라이언트 시크릿 입력
            scope:
              - profile
              - email

          # ================= NAVER ==================
          naver:
            client-id: YOUR_NAVER_CLIENT_ID_HERE # 여기에 네이버 클라이언트 ID 입력
            client-secret: YOUR_NAVER_CLIENT_SECRET_HERE # 여기에 네이버 클라이언트 시크릿 입력
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  oauth2:
    redirect-uri: http://localhost:3000/oauth/redirect

# Server Port
server:
  port: 8080

# Springdoc (Swagger UI)
springdoc:
  swagger-ui:
    path: /swagger-ui.html


# JWT
jwt:
  secret: 'wJalr7JtL4VklA4aEW/B1A3oA8gQyJ5aA+8eN/aT4bHq8cW+lY6zR/aN9vY8bV7cW+lY6zR/aN9vY8bV7cW+lY6zR/aN9vY8bV7cW+lY6zR/aN9vY8bV7c='
  token-validity-in-seconds: 86400 # 1일 (Access Token)
  refresh-token-validity-in-seconds: 604800 # 7일 (Refresh Token)

# File
file:
  upload-dir: uploads/

# Cloudflare
cloudflare:
  api:
    token: 4JLvqCWFDngI5MTGMMAAowX-ZrZChJUE5i1eBjGe
  account:
    id: ef7bc155ee8a5d229c2086d399721c87
  base:
    url: https://api.cloudflare.com/client/v4
